# example netlify.toml
[build]
  command = "yarn run build"
  functions = "functions"
  publish = "dist"

# [dev] # https://github.com/netlify/netlify-dev-plugin#project-detection
#   command = "yarn start" # Command to start your dev server
#   port = 3000 # Port that the dev server will be listening on
#   publish = "dist" # Folder with the static content for _redirect file

## Uncomment to use this redirect for Single Page Applications. 
## Not needed for static site generators.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

## more info https://www.netlify.com/docs/netlify-toml-reference/
